# Generated by Django 5.0.2 on 2024-03-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoteMakerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtubeLink', models.CharField(max_length=100)),
                ('processing', models.CharField(max_length=100)),
                ('noteType', models.CharField(max_length=100)),
            ],
        ),
    ]
