# Generated by Django 4.2.7 on 2023-11-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoteMakerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtubeLink', models.CharField(max_length=100)),
                ('processing', models.CharField(max_length=100)),
                ('noteType', models.CharField(max_length=100)),
                ('noteDoc', models.FileField(blank=True, null=True, upload_to='notes/')),
            ],
        ),
    ]
